In [16]:
# import libraries
import numpy as np
import pandas as pd

In [18]:
# load dataset and clean the data
df = pd.read_csv("all_players.csv")
df = df.dropna()
df = df.drop_duplicates()
df

,Player,Club,POS,GP,GS,MINS,G,A,SHTS,SOG,...,RdA,A/90min,FC,FS,OFF,YC,RC,SOG%,Year,Season
0,Roy Lassiter,TB,F,30,30,2580,27,4,76,49,...,2,0.14,20,39,70,2,0,64.47,1996,reg
1,Raul Diaz Arce,DC,F,28,28,2351,23,2,100,49,...,2,0.08,32,26,35,6,1,49.00,1996,reg
2,Eduardo Hurtado,LA,F,26,26,2323,21,7,87,56,...,3,0.27,48,26,25,5,0,64.37,1996,reg
3,Preki,KC,M,32,32,2880,18,13,140,61,...,4,0.41,26,44,7,3,0,43.57,1996,reg
4,Brian McBride,CLB,F,28,28,2307,17,3,79,44,...,1,0.12,21,46,10,0,0,55.70,1996,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15296,Sebastian Mendez,ORL,M,19,11,1087,0,0,17,3,...,0,0.00,32,9,1,4,1,17.65,2020,reg
15297,Kelyn Rowe,NE,M,16,10,896,0,0,17,4,...,0,0.00,13,4,0,3,0,23.53,2020,reg
15298,Siem de Jong,CIN,M,15,8,793,0,0,18,5,...,0,0.00,7,8,1,0,0,27.78,2020,reg
15299,Maxime Chanot,NYC,D,20,20,1712,0,0,19,4,...,0,0.00,18,6,1,5,1,21.05,2020,reg
15300,Nicolas Figal,MIA,D,21,21,1746,0,0,22,9,...,0,0.00,22,26,0,4,0,40.91,2020,reg

In [24]:
# reset index
df = df.reset_index()
df

,index,Player,Club,POS,GP,GS,MINS,G,A,SHTS,...,RdA,A/90min,FC,FS,OFF,YC,RC,SOG%,Year,Season
0,0,Roy Lassiter,TB,F,30,30,2580,27,4,76,...,2,0.14,20,39,70,2,0,64.47,1996,reg
1,1,Raul Diaz Arce,DC,F,28,28,2351,23,2,100,...,2,0.08,32,26,35,6,1,49.00,1996,reg
2,2,Eduardo Hurtado,LA,F,26,26,2323,21,7,87,...,3,0.27,48,26,25,5,0,64.37,1996,reg
3,3,Preki,KC,M,32,32,2880,18,13,140,...,4,0.41,26,44,7,3,0,43.57,1996,reg
4,4,Brian McBride,CLB,F,28,28,2307,17,3,79,...,1,0.12,21,46,10,0,0,55.70,1996,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8041,15296,Sebastian Mendez,ORL,M,19,11,1087,0,0,17,...,0,0.00,32,9,1,4,1,17.65,2020,reg
8042,15297,Kelyn Rowe,NE,M,16,10,896,0,0,17,...,0,0.00,13,4,0,3,0,23.53,2020,reg
8043,15298,Siem de Jong,CIN,M,15,8,793,0,0,18,...,0,0.00,7,8,1,0,0,27.78,2020,reg
8044,15299,Maxime Chanot,NYC,D,20,20,1712,0,0,19,...,0,0.00,18,6,1,5,1,21.05,2020,reg
8045,15300,Nicolas Figal,MIA,D,21,21,1746,0,0,22,...,0,0.00,22,26,0,4,0,40.91,2020,reg

In [30]:
df = df.drop(columns=["index"])
df

,Player,Club,POS,GP,GS,MINS,G,A,SHTS,SOG,...,RdA,A/90min,FC,FS,OFF,YC,RC,SOG%,Year,Season
0,Roy Lassiter,TB,F,30,30,2580,27,4,76,49,...,2,0.14,20,39,70,2,0,64.47,1996,reg
1,Raul Diaz Arce,DC,F,28,28,2351,23,2,100,49,...,2,0.08,32,26,35,6,1,49.00,1996,reg
2,Eduardo Hurtado,LA,F,26,26,2323,21,7,87,56,...,3,0.27,48,26,25,5,0,64.37,1996,reg
3,Preki,KC,M,32,32,2880,18,13,140,61,...,4,0.41,26,44,7,3,0,43.57,1996,reg
4,Brian McBride,CLB,F,28,28,2307,17,3,79,44,...,1,0.12,21,46,10,0,0,55.70,1996,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8041,Sebastian Mendez,ORL,M,19,11,1087,0,0,17,3,...,0,0.00,32,9,1,4,1,17.65,2020,reg
8042,Kelyn Rowe,NE,M,16,10,896,0,0,17,4,...,0,0.00,13,4,0,3,0,23.53,2020,reg
8043,Siem de Jong,CIN,M,15,8,793,0,0,18,5,...,0,0.00,7,8,1,0,0,27.78,2020,reg
8044,Maxime Chanot,NYC,D,20,20,1712,0,0,19,4,...,0,0.00,18,6,1,5,1,21.05,2020,reg
8045,Nicolas Figal,MIA,D,21,21,1746,0,0,22,9,...,0,0.00,22,26,0,4,0,40.91,2020,reg